language: python
sudo: false

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install cairo python3-dev libffi-dev
install:
  - pip install -U tox codecov
script:
  - tox
after_success:
  - codecov

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: informatics-lab/metglyphs
    condition: "$TOXENV = py35"
